const testArrays = {
  progCMaj: [
    {
      id: 3,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major',
      notation: 'C',
      variation: '1',
      chord_code: '0,x,2,1,o,0,o',
      tag: 'basic, beginner, open',
    },
    {
      id: 7,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major',
      notation: 'G',
      variation: '1',
      chord_code: '0,2,1,o,o,2,2',
      tag: 'basic, beginner, open',
    },
    {
      id: 8,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor',
      notation: 'Am',
      variation: '1',
      chord_code: '0,x,o,1,1,0,o',
      tag: 'basic, beginner, open',
    },
    {
      id: 37,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor 7 sus4',
      notation: 'Am',
      variation: '2',
      chord_code: '0,x,o,1,o,2,2',
      tag: 'jazz, open, seventh',
    },
    {
      id: 39,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major add9',
      notation: 'C',
      variation: '2',
      chord_code: '0,x,2,1,o,2,2',
      tag: 'jazz, open',
    },
    {
      id: 40,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major 7',
      notation: 'C',
      variation: '3',
      chord_code: '3,x,0,2,o,o,o',
      tag: 'dissonant, open, seventh',
    },
    {
      id: 43,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major',
      notation: 'G',
      variation: '3',
      chord_code: '10,x,x,2,o,2,o',
      tag: 'intermediate',
    },
    {
      id: 44,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major 7',
      notation: 'C',
      variation: '4',
      chord_code: '8,0,2,1,1,0,0,b',
      tag: 'intermediate, seventh',
    },
    {
      id: 46,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major 7',
      notation: 'G',
      variation: '4',
      chord_code: '0,2,1,o,o,o,0',
      tag: 'intermediate, seventh',
    },
    {
      id: 52,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major/D',
      notation: 'G',
      variation: '5',
      chord_code: '7,x,x,o,0,1,0',
      tag: 'intermediate',
    },
    {
      id: 53,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor 9',
      notation: 'Am',
      variation: '3',
      chord_code: '5,x,o,0,0,0,2,b',
      tag: 'intermediate, jazz, mellow',
    },
    {
      id: 58,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G5',
      notation: 'G',
      variation: '6',
      chord_code: '3,0,2,2,x,x,x',
      tag: 'basic, rock, blues, power chord',
    },
    {
      id: 59,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C5',
      notation: 'C',
      variation: '5',
      chord_code: '3,0,2,2,x,x,x',
      tag: 'basic, rock, blues, power chord',
    },
    {
      id: 65,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Cadd9',
      notation: 'C',
      variation: '6',
      chord_code: '0,o,2,x,o,2,o',
      tag: 'intermediate, rock, blues',
    },
    {
      id: 69,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'GMaj7 add#11',
      notation: 'G',
      variation: '7',
      chord_code: '3,0,2,1,3,o,x',
      tag: 'advanced, seventh',
    },
    {
      id: 70,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin#6 add9',
      notation: 'Am',
      variation: '4',
      chord_code: '4,x,o,0,1,1,3',
      tag: 'advanced',
    },
    {
      id: 74,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'CMaj7/G',
      notation: 'C',
      variation: '7',
      chord_code: '0,2,2,1,o,o,o',
      tag: 'intermediate, seventh',
    },
    {
      id: 75,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G5 add9',
      notation: 'G',
      variation: '8',
      chord_code: '0,2,x,o,1,2,2',
      tag: 'intermediate, power chord',
    },
    {
      id: 77,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin7/E',
      notation: 'Am',
      variation: '5',
      chord_code: '12,0,0,2,o,1,3',
      tag: 'advanced, seventh',
    },
    {
      id: 83,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin6',
      notation: 'Am',
      variation: '6',
      chord_code: '5,x,o,0,1,1,o',
      tag: 'intermediate',
    },
    {
      id: 86,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor',
      notation: 'Am',
      variation: '7',
      chord_code: '9,x,o,o,1,2,0',
      tag: 'intermediate',
    },
    {
      id: 92,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'GMaj7/B',
      notation: 'G',
      variation: '9',
      chord_code: '7,0,3,2,0,0,0,b',
      tag: 'advanced, seventh',
    },
    {
      id: 93,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin/Maj7',
      notation: 'Am',
      variation: '8',
      chord_code: '5,x,o,1,0,0,o',
      tag: 'advanced, seventh, jazz',
    },
  ],


  fullCMaj: [
    {
      id: 3,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major',
      notation: 'C',
      variation: '1',
      chord_code: '0,x,2,1,o,0,o',
      tag: 'basic, beginner, open',
    },
    {
      id: 6,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'F major',
      notation: 'F',
      variation: '1',
      chord_code: '0,0,2,2,1,0,0,b',
      tag: 'basic, open',
    },
    {
      id: 7,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major',
      notation: 'G',
      variation: '1',
      chord_code: '0,2,1,o,o,2,2',
      tag: 'basic, beginner, open',
    },
    {
      id: 8,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor',
      notation: 'Am',
      variation: '1',
      chord_code: '0,x,o,1,1,0,o',
      tag: 'basic, beginner, open',
    },
    {
      id: 10,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'D minor',
      notation: 'Dm',
      variation: '1',
      chord_code: '0,x,x,o,1,2,0',
      tag: 'basic, beginner, open',
    },
    {
      id: 11,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'E minor',
      notation: 'Em',
      variation: '1',
      chord_code: '0,o,1,1,o,o,o',
      tag: 'basic, beginner, open',
    },
    {
      id: 13,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'B diminished',
      notation: 'Bdim',
      variation: '1',
      chord_code: '0,x,1,2,3,2,x',
      tag: 'diminished',
    },
    {
      id: 37,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor 7 sus4',
      notation: 'Am',
      variation: '2',
      chord_code: '0,x,o,1,o,2,2',
      tag: 'jazz, open, seventh',
    },
    {
      id: 38,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'E minor 7',
      notation: 'Em',
      variation: '2',
      chord_code: '0,o,1,1,o,2,2',
      tag: 'jazz, open, seventh',
    },
    {
      id: 39,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major add9',
      notation: 'C',
      variation: '2',
      chord_code: '0,x,2,1,o,2,2',
      tag: 'jazz, open',
    },
    {
      id: 40,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major 7',
      notation: 'C',
      variation: '3',
      chord_code: '3,x,0,2,o,o,o',
      tag: 'dissonant, open, seventh',
    },
    {
      id: 41,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'E minor 9',
      notation: 'Em',
      variation: '3',
      chord_code: '0,o,1,o,o,2,1',
      tag: 'dissonant, open',
    },
    {
      id: 43,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major',
      notation: 'G',
      variation: '3',
      chord_code: '10,x,x,2,o,2,o',
      tag: 'intermediate',
    },
    {
      id: 44,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C major 7',
      notation: 'C',
      variation: '4',
      chord_code: '8,0,2,1,1,0,0,b',
      tag: 'intermediate, seventh',
    },
    {
      id: 45,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'E minor 7',
      notation: 'Em',
      variation: '4',
      chord_code: '0,o,x,1,3,2,2',
      tag: 'intermediate, seventh, dark, brooding',
    },
    {
      id: 46,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major 7',
      notation: 'G',
      variation: '4',
      chord_code: '0,2,1,o,o,o,0',
      tag: 'intermediate, seventh',
    },
    {
      id: 52,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G major/D',
      notation: 'G',
      variation: '5',
      chord_code: '7,x,x,o,0,1,0',
      tag: 'intermediate',
    },
    {
      id: 53,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor 9',
      notation: 'Am',
      variation: '3',
      chord_code: '5,x,o,0,0,0,2,b',
      tag: 'intermediate, jazz, mellow',
    },
    {
      id: 58,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G5',
      notation: 'G',
      variation: '6',
      chord_code: '3,0,2,2,x,x,x',
      tag: 'basic, rock, blues, power chord',
    },
    {
      id: 59,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'C5',
      notation: 'C',
      variation: '5',
      chord_code: '3,0,2,2,x,x,x',
      tag: 'basic, rock, blues, power chord',
    },
    {
      id: 65,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Cadd9',
      notation: 'C',
      variation: '6',
      chord_code: '0,o,2,x,o,2,o',
      tag: 'intermediate, rock, blues',
    },
    {
      id: 69,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'GMaj7 add#11',
      notation: 'G',
      variation: '7',
      chord_code: '3,0,2,1,3,o,x',
      tag: 'advanced, seventh',
    },
    {
      id: 70,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin#6 add9',
      notation: 'Am',
      variation: '4',
      chord_code: '4,x,o,0,1,1,3',
      tag: 'advanced',
    },
    {
      id: 71,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Emin11',
      notation: 'Em',
      variation: '5',
      chord_code: '5,o,2,0,2,3,0,b',
      tag: 'advanced',
    },
    {
      id: 72,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Emin11',
      notation: 'Em',
      variation: '6',
      chord_code: '12,o,0,0,0,o,o',
      tag: 'advanced',
    },
    {
      id: 74,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'CMaj7/G',
      notation: 'C',
      variation: '7',
      chord_code: '0,2,2,1,o,o,o',
      tag: 'intermediate, seventh',
    },
    {
      id: 75,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'G5 add9',
      notation: 'G',
      variation: '8',
      chord_code: '0,2,x,o,1,2,2',
      tag: 'intermediate, power chord',
    },
    {
      id: 77,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin7/E',
      notation: 'Am',
      variation: '5',
      chord_code: '12,0,0,2,o,1,3',
      tag: 'advanced, seventh',
    },
    {
      id: 78,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'E minor',
      notation: 'Em',
      variation: '5',
      chord_code: '5,x,2,0,o,o,o',
      tag: 'intermediate',
    },
    {
      id: 82,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Dmin add9/A',
      notation: 'Dm',
      variation: '2',
      chord_code: '0,x,o,2,1,2,o',
      tag: 'intermediate',
    },
    {
      id: 83,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin6',
      notation: 'Am',
      variation: '6',
      chord_code: '5,x,o,0,1,1,o',
      tag: 'intermediate',
    },
    {
      id: 84,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Dmin9/A',
      notation: 'Dm',
      variation: '3',
      chord_code: '5,x,o,2,0,1,o',
      tag: 'intermediate',
    },
    {
      id: 85,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Emin7/A',
      notation: 'Em',
      variation: '6',
      chord_code: '7,x,o,2,0,1,o',
      tag: 'intermediate, seventh',
    },
    {
      id: 86,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'A minor',
      notation: 'Am',
      variation: '7',
      chord_code: '9,x,o,o,1,2,0',
      tag: 'intermediate',
    },
    {
      id: 88,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'FMaj9',
      notation: 'F',
      variation: '2',
      chord_code: '7,x,1,0,2,1,x',
      tag: 'intermediate, jazz, pop, indie',
    },
    {
      id: 91,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Dmin13',
      notation: 'Dm',
      variation: '4',
      chord_code: '5,x,0,2,0,1,2,b',
      tag: 'intermediate, jazz, pop, indie',
    },
    {
      id: 92,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'GMaj7/B',
      notation: 'G',
      variation: '9',
      chord_code: '7,0,3,2,0,0,0,b',
      tag: 'advanced, seventh',
    },
    {
      id: 93,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Amin/Maj7',
      notation: 'Am',
      variation: '8',
      chord_code: '5,x,o,1,0,0,o',
      tag: 'advanced, seventh, jazz',
    },
    {
      id: 113,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'Emin7',
      notation: 'Em',
      variation: '7',
      chord_code: '7,x,0,2,0,1,0,b',
      tag: 'advanced, jazz, seventh',
    },
    {
      id: 120,
      tonic: 'C',
      second: 'Dm',
      third: 'Em',
      fourth: 'F',
      fifth: 'G',
      sixth: 'Am',
      seventh: 'Bdim',
      chord_name: 'FMaj/A',
      notation: 'F',
      variation: '3',
      chord_code: '0,x,o,2,1,0,0,b',
      tag: 'intermediate, barre',
    },
  ],
};

export default testArrays;
